- name: install httpd package
  tags: apache, centos, httpd
  dnf:
    name: 
      - httpd
      - php
    state: latest
    update_cache: yes
  when: ansible_distribution =="CentOS" 

- name: install apache2 package
  tags: apache, ubuntu, apache2
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  
